//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltrasonicTestingForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UltrasonicTestingForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0019.
        /// </summary>
        internal static string AcousticAttenuation {
            get {
                return ResourceManager.GetString("AcousticAttenuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0008.
        /// </summary>
        internal static string AcousticImpedancePEC {
            get {
                return ResourceManager.GetString("AcousticImpedancePEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0013.
        /// </summary>
        internal static string AcousticImpedanceTO {
            get {
                return ResourceManager.GetString("AcousticImpedanceTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0017.
        /// </summary>
        internal static string AreaPEC {
            get {
                return ResourceManager.GetString("AreaPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0007.
        /// </summary>
        internal static string DensityPEC {
            get {
                return ResourceManager.GetString("DensityPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0011.
        /// </summary>
        internal static string DensityTO {
            get {
                return ResourceManager.GetString("DensityTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0016.
        /// </summary>
        internal static string FraunhoferDistance {
            get {
                return ResourceManager.GetString("FraunhoferDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0003.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0015.
        /// </summary>
        internal static string FresnelDistance {
            get {
                return ResourceManager.GetString("FresnelDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0012.
        /// </summary>
        internal static string FsplTO {
            get {
                return ResourceManager.GetString("FsplTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_calc_white {
            get {
                object obj = ResourceManager.GetObject("icon_calc_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_file_white {
            get {
                object obj = ResourceManager.GetObject("icon_file_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_info_white {
            get {
                object obj = ResourceManager.GetObject("icon_info_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_property_white {
            get {
                object obj = ResourceManager.GetObject("icon_property_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconProject {
            get {
                object obj = ResourceManager.GetObject("IconProject", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0020.
        /// </summary>
        internal static string InAmplitude {
            get {
                return ResourceManager.GetString("InAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0018.
        /// </summary>
        internal static string IntensityTransmittance {
            get {
                return ResourceManager.GetString("IntensityTransmittance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0005.
        /// </summary>
        internal static string MaterialPEC {
            get {
                return ResourceManager.GetString("MaterialPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0009.
        /// </summary>
        internal static string MaterialTO {
            get {
                return ResourceManager.GetString("MaterialTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PEC {
            get {
                object obj = ResourceManager.GetObject("PEC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0001.
        /// </summary>
        internal static string RadiusPEC {
            get {
                return ResourceManager.GetString("RadiusPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0006.
        /// </summary>
        internal static string SpeedOfSoundPEC {
            get {
                return ResourceManager.GetString("SpeedOfSoundPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0010.
        /// </summary>
        internal static string SpeedOfSoundTO {
            get {
                return ResourceManager.GetString("SpeedOfSoundTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0004.
        /// </summary>
        internal static string ThicknessTO {
            get {
                return ResourceManager.GetString("ThicknessTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0002.
        /// </summary>
        internal static string WaveAmplitude {
            get {
                return ResourceManager.GetString("WaveAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap waveBottom {
            get {
                object obj = ResourceManager.GetObject("waveBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0014.
        /// </summary>
        internal static string Wavelength {
            get {
                return ResourceManager.GetString("Wavelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap waveTop {
            get {
                object obj = ResourceManager.GetObject("waveTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
